export { default as CameraPoints } from './cameraPoints.vue'
export { default as InfoPoints } from './infoPoints.vue'
export { default as LayersFilters } from './layersFilters.vue'
export { default as MapboxComp } from './mapboxComp.vue'
export { default as MapboxFilters } from './mapboxFilters.vue'
export { default as TablePoints } from './tablePoints.vue'
