export { default as FooterComp } from './footerComp.vue'
export { default as HeaderComp } from './headerComp.vue'
export { default as LoadingComp } from './loadingComp.vue'
export { default as MobileMenu } from './mobileMenu.vue'
export { default as ThemeSwitcher } from './themeSwitcher.vue'
